version: "3"
services:
  kn-utils-server:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 3002:3002
    command: "npm run start"
networks:
  kn-net:
    driver: bridge